# Single source of truth for the site.
# Edit here, then run:  python3 site/build.py
#
# Adding an app  -> append to APPS below.
# Adding a language -> add a code to LANGS and a block to STRINGS.

LANGS = [
    ("en", "English",          "en"),
    ("vi", "Tiếng Việt",       "vi"),
    ("ja", "日本語",            "ja"),
    ("ko", "한국어",            "ko"),
    ("zh", "中文",              "zh-Hans"),
    ("th", "ไทย",              "th"),
    ("es", "Español",          "es"),
    ("fr", "Français",         "fr"),
    ("id", "Bahasa Indonesia", "id"),
    ("el", "Ελληνικά",         "el"),
]

# Apps. Names/taglines that are brand identity stay in English on every locale;
# `desc` and `meta` are translated per language via STRINGS[lang]["apps"][slug].
APPS = [
    dict(
        slug="toeic-test",
        name="New Practice for TOEIC® Test",
        site="https://new-toeic-test.pages.dev/",
        icon="images/toeic-test-icon.png",
        accent="#3b82f6",
        featured=True,
        badge="badge_popular",
        rating="4.7",
        installs="200,000+",
        android="https://play.google.com/store/apps/details?id=com.tvt.toeictest.newformat2019",
        ios="https://apps.apple.com/vn/app/new-toeic-test/id1462727474",
    ),
    dict(
        slug="chess-ninja",
        name="Chess Ninja: Wave Survival",
        site="https://chess-ninja.pages.dev/",
        icon="images/chess-ninja-icon.png",
        accent="#dc2626",
        featured=False,
        badge="badge_new",
        rating=None,
        installs=None,
        android="https://play.google.com/store/apps/details?id=com.tvt.chess.ninja",
        ios="https://apps.apple.com/app/chess-ninja-wave-survival/id6807704026",
    ),
    dict(
        slug="crack-the-code",
        name="Crack the Code Pro",
        site="https://crack-the-code-pro.pages.dev/",
        icon="images/crack-the-code-icon.png",
        accent="#f59e0b",
        featured=False,
        badge=None,
        rating="4.6",
        installs="17,000+",
        android="https://play.google.com/store/apps/details?id=com.tvt.crackthecode",
        ios="https://apps.apple.com/vn/app/crack-the-code-pro/id1510109064",
    ),
    dict(
        slug="vstep-practice",
        name="VSTEP Practice",
        site="https://thi-vstep.pages.dev/",
        icon="images/vstep-icon.png",
        accent="#2952e3",
        featured=False,
        badge="badge_new",
        rating=None,
        installs=None,
        android="https://play.google.com/store/apps/details?id=com.tvt.vstep",
        ios=None,
    ),
]

INSTALL_TOTAL = "217,000"

STRINGS = {
"en": dict(
    page_title="TvTroid — Apps that make learning feel like play",
    meta_desc="Simple, well-crafted mobile apps for learning and fun. Over 217,000 people use our TOEIC®, puzzle, and chess apps.",
    nav_apps="Apps", nav_about="About", nav_cta="Get the apps",
    eyebrow_hero="Made by TvTroid",
    hero_l1="Apps that make", hero_l2="learning feel like play",
    hero_sub="Over 217,000 people use our apps to ace the TOEIC® and sharpen their minds with puzzles — free to download, easy to love.",
    btn_explore="Explore the apps", btn_learn="Learn more",
    stat_installs="Installs", stat_rating="Avg. rating", stat_apps="Apps shipped",
    eyebrow_apps="Our apps", apps_h2="Pick your next favorite app",
    apps_sub="Free to download. Built to be simple, fast, and genuinely useful.",
    badge_popular="Most popular", badge_new="New",
    installs_suffix="installs",
    eyebrow_about="About TvTroid", about_h2="Small team. Simple apps. No fluff.",
    about_p="We're an indie studio focused on building useful, no-nonsense mobile apps — from spaced-repetition learning tools to addictive puzzle games. Every app is designed to do one thing well, load fast, and respect your time.",
    f1_h="Fast & lightweight", f1_p="No bloat, no clutter — just the features you actually need.",
    f2_h="Built with purpose", f2_p="Every app solves a real problem, backed by real learning science.",
    f3_h="Privacy respected", f3_p="We keep data collection minimal and transparent. Always.",
    cta_h="Ready to give it a try?", cta_p="Download any of our apps today — free, fast, and just one tap away.",
    cta_btn="Browse all apps",
    footer_tag="We build apps people love to use",
    privacy="Privacy Policy", rights="TvTroid. All rights reserved.",
    lang_label="Language",
    apps={
        "toeic-test": dict(tagline="Master the TOEIC® New Format with spaced repetition",
            desc="Over 1,000 real TOEIC® questions with a smart spaced-repetition engine that helps you retain vocabulary and grammar for good — not just until the test."),
        "chess-ninja": dict(tagline="How long can you last?",
            desc="Capture enemy pieces to steal their powers, chain kills for combo bonuses up to ×8, and survive endless waves on a single board. Free to play, no account needed.",
            meta=["6 playable pieces", "Free to play"]),
        "crack-the-code": dict(tagline="An endless puzzle that keeps you guessing",
            desc="Find the correct numbers hidden in each riddle to unlock the key. Simple to learn, hard to put down — compete with friends across endless levels."),
        "vstep-practice": dict(tagline="Practice all 4 VSTEP skills in real exam format",
            desc="Listening, Reading, Writing, and Speaking mock tests matching the real VSTEP.3-5 timing and structure, with bilingual transcripts and smart review reminders. Free, works offline.",
            meta=["4 skills covered", "Works offline"]),
    },
),
"vi": dict(
    page_title="TvTroid — Ứng dụng biến việc học thành niềm vui",
    meta_desc="Ứng dụng di động đơn giản, tinh tế để học và giải trí. Hơn 217.000 người đang dùng các ứng dụng TOEIC®, giải đố và cờ của chúng tôi.",
    nav_apps="Ứng dụng", nav_about="Giới thiệu", nav_cta="Tải ứng dụng",
    eyebrow_hero="Được tạo bởi TvTroid",
    hero_l1="Ứng dụng biến", hero_l2="việc học thành niềm vui",
    hero_sub="Hơn 217.000 người dùng ứng dụng của chúng tôi để chinh phục TOEIC® và rèn luyện trí não với các trò giải đố — miễn phí, dễ yêu thích.",
    btn_explore="Khám phá ứng dụng", btn_learn="Tìm hiểu thêm",
    stat_installs="Lượt cài đặt", stat_rating="Đánh giá TB", stat_apps="Ứng dụng đã phát hành",
    eyebrow_apps="Ứng dụng của chúng tôi", apps_h2="Chọn ứng dụng yêu thích tiếp theo",
    apps_sub="Miễn phí tải về. Đơn giản, nhanh và thực sự hữu ích.",
    badge_popular="Phổ biến nhất", badge_new="Mới",
    installs_suffix="lượt cài đặt",
    eyebrow_about="Về TvTroid", about_h2="Nhóm nhỏ. Ứng dụng đơn giản. Không rườm rà.",
    about_p="Chúng tôi là một studio độc lập tập trung xây dựng các ứng dụng di động hữu ích, không rườm rà — từ công cụ học theo phương pháp lặp lại ngắt quãng đến trò chơi giải đố cuốn hút. Mỗi ứng dụng được thiết kế để làm tốt một việc, tải nhanh và tôn trọng thời gian của bạn.",
    f1_h="Nhanh & nhẹ", f1_p="Không nặng nề, không rối mắt — chỉ những tính năng bạn thực sự cần.",
    f2_h="Xây dựng có mục đích", f2_p="Mỗi ứng dụng giải quyết một vấn đề thực tế, dựa trên khoa học học tập.",
    f3_h="Tôn trọng quyền riêng tư", f3_p="Chúng tôi thu thập dữ liệu ở mức tối thiểu và minh bạch. Luôn luôn.",
    cta_h="Sẵn sàng dùng thử?", cta_p="Tải bất kỳ ứng dụng nào hôm nay — miễn phí, nhanh chóng, chỉ một chạm.",
    cta_btn="Xem tất cả ứng dụng",
    footer_tag="Chúng tôi tạo ra những ứng dụng được yêu thích",
    privacy="Chính sách bảo mật", rights="TvTroid. Bảo lưu mọi quyền.",
    lang_label="Ngôn ngữ",
    apps={
        "toeic-test": dict(tagline="Chinh phục TOEIC® Format Mới với phương pháp lặp lại ngắt quãng",
            desc="Hơn 1.000 câu hỏi TOEIC® thực tế cùng công nghệ lặp lại ngắt quãng thông minh giúp bạn ghi nhớ từ vựng và ngữ pháp lâu dài — không chỉ đến ngày thi."),
        "chess-ninja": dict(tagline="Bạn trụ được bao lâu?",
            desc="Ăn quân địch để cướp sức mạnh của chúng, nối chuỗi tiêu diệt để nhân combo lên ×8, và sống sót qua vô tận các đợt tấn công trên một bàn cờ. Chơi miễn phí, không cần tài khoản.",
            meta=["6 quân cờ chơi được", "Miễn phí"]),
        "crack-the-code": dict(tagline="Trò giải đố bất tận khiến bạn phải suy nghĩ",
            desc="Tìm các con số đúng ẩn trong mỗi câu đố để mở khóa. Dễ học, khó bỏ xuống — thi đấu cùng bạn bè qua vô số màn chơi."),
        "vstep-practice": dict(tagline="Luyện đủ 4 kỹ năng VSTEP theo đúng cấu trúc đề thi thật",
            desc="Đề thi thử Nghe, Đọc, Viết, Nói sát cấu trúc và thời gian đề thi VSTEP.3-5, có transcript song ngữ và nhắc ôn tập thông minh. Miễn phí, học offline.",
            meta=["Đủ 4 kỹ năng", "Học offline"]),
    },
),
"ja": dict(
    page_title="TvTroid — 学びを遊びに変えるアプリ",
    meta_desc="学習と娯楽のためのシンプルで丁寧に作られたモバイルアプリ。217,000人以上がTOEIC®・パズル・チェスアプリを利用しています。",
    nav_apps="アプリ", nav_about="概要", nav_cta="アプリを入手",
    eyebrow_hero="TvTroid制作",
    hero_l1="学びを", hero_l2="遊びに変えるアプリ",
    hero_sub="217,000人以上が、TOEIC®対策と頭脳を鍛えるパズルに私たちのアプリを使っています — 無料でダウンロード、すぐに好きになります。",
    btn_explore="アプリを見る", btn_learn="詳しく見る",
    stat_installs="インストール数", stat_rating="平均評価", stat_apps="リリース済みアプリ",
    eyebrow_apps="アプリ一覧", apps_h2="次のお気に入りを見つけよう",
    apps_sub="無料ダウンロード。シンプルで速く、本当に役立つように作られています。",
    badge_popular="一番人気", badge_new="新着",
    installs_suffix="インストール",
    eyebrow_about="TvTroidについて", about_h2="小さなチーム。シンプルなアプリ。無駄なし。",
    about_p="私たちは、役に立つ無駄のないモバイルアプリ作りに注力するインディースタジオです — 間隔反復の学習ツールから夢中になるパズルゲームまで。どのアプリも一つのことを上手くこなし、素早く起動し、あなたの時間を大切にするよう設計されています。",
    f1_h="高速&軽量", f1_p="肥大化も雑然さもなく、本当に必要な機能だけ。",
    f2_h="目的を持った設計", f2_p="どのアプリも実際の課題を、学習科学の裏付けとともに解決します。",
    f3_h="プライバシーを尊重", f3_p="データ収集は最小限かつ透明に。常に。",
    cta_h="試してみませんか？", cta_p="今日どれでもダウンロード — 無料、高速、ワンタップ。",
    cta_btn="すべてのアプリを見る",
    footer_tag="愛されるアプリを作っています",
    privacy="プライバシーポリシー", rights="TvTroid. All rights reserved.",
    lang_label="言語",
    apps={
        "toeic-test": dict(tagline="間隔反復でTOEIC®新形式を攻略",
            desc="1,000問以上の実践的なTOEIC®問題と、賢い間隔反復エンジンで語彙と文法を長期的に定着 — 試験当日だけでなく、ずっと。"),
        "chess-ninja": dict(tagline="どこまで生き残れる？",
            desc="敵の駒を取ってその能力を奪い、連続撃破で最大×8のコンボボーナスを狙い、1つの盤上で無限に押し寄せる波を生き延びよう。無料プレイ、アカウント不要。",
            meta=["6種類の駒", "基本無料"]),
        "crack-the-code": dict(tagline="頭を悩ませ続ける無限パズル",
            desc="各ヒントに隠された正しい数字を見つけて鍵を開けよう。ルールは簡単、やめられない面白さ — 友達と競い合える無限のレベル。"),
        "vstep-practice": dict(tagline="VSTEP4技能を本番形式で練習",
            desc="リスニング・リーディング・ライティング・スピーキングの模擬試験が、本番のVSTEP.3-5と同じ構成・時間で受けられます。バイリンガル文字起こし付きでスマートな復習リマインダーも。無料・オフライン対応。",
            meta=["4技能に対応", "オフライン対応"]),
    },
),
"ko": dict(
    page_title="TvTroid — 배움을 놀이로 만드는 앱",
    meta_desc="학습과 재미를 위한 심플하고 정교한 모바일 앱. 217,000명 이상이 TOEIC®, 퍼즐, 체스 앱을 사용합니다.",
    nav_apps="앱", nav_about="소개", nav_cta="앱 받기",
    eyebrow_hero="TvTroid 제작",
    hero_l1="배움을", hero_l2="놀이로 만드는 앱",
    hero_sub="217,000명 이상이 TOEIC® 정복과 두뇌 단련 퍼즐에 우리 앱을 사용합니다 — 무료 다운로드, 쉽게 빠져듭니다.",
    btn_explore="앱 둘러보기", btn_learn="더 알아보기",
    stat_installs="설치 수", stat_rating="평균 평점", stat_apps="출시한 앱",
    eyebrow_apps="우리 앱", apps_h2="다음 최애 앱을 골라보세요",
    apps_sub="무료 다운로드. 심플하고 빠르며 진짜 유용하게 만들었습니다.",
    badge_popular="가장 인기", badge_new="신규",
    installs_suffix="설치",
    eyebrow_about="TvTroid 소개", about_h2="작은 팀. 심플한 앱. 군더더기 없이.",
    about_p="저희는 쓸모 있고 군더더기 없는 모바일 앱을 만드는 인디 스튜디오입니다 — 간격 반복 학습 도구부터 중독성 있는 퍼즐 게임까지. 모든 앱은 한 가지를 잘 해내고, 빠르게 실행되며, 여러분의 시간을 존중하도록 설계되었습니다.",
    f1_h="빠르고 가볍게", f1_p="군더더기도 복잡함도 없이 — 정말 필요한 기능만.",
    f2_h="목적이 있는 설계", f2_p="모든 앱은 실제 문제를 학습 과학에 근거해 해결합니다.",
    f3_h="개인정보 존중", f3_p="데이터 수집은 최소한으로, 투명하게. 언제나.",
    cta_h="한번 사용해 보시겠어요?", cta_p="오늘 아무 앱이나 받아보세요 — 무료, 빠르게, 한 번의 탭으로.",
    cta_btn="전체 앱 보기",
    footer_tag="사랑받는 앱을 만듭니다",
    privacy="개인정보처리방침", rights="TvTroid. All rights reserved.",
    lang_label="언어",
    apps={
        "toeic-test": dict(tagline="간격 반복으로 TOEIC® 신유형 정복",
            desc="1,000개 이상의 실전 TOEIC® 문제와 스마트 간격 반복 엔진으로 어휘와 문법을 오래 기억하세요 — 시험 당일까지만이 아니라."),
        "chess-ninja": dict(tagline="얼마나 버틸 수 있나요?",
            desc="적의 기물을 잡아 그 능력을 빼앗고, 연속 처치로 최대 ×8 콤보 보너스를 쌓으며, 하나의 보드에서 끝없는 웨이브를 버텨내세요. 무료 플레이, 계정 불필요.",
            meta=["6가지 기물", "무료 플레이"]),
        "crack-the-code": dict(tagline="계속 머리를 쓰게 하는 끝없는 퍼즐",
            desc="각 힌트에 숨겨진 정확한 숫자를 찾아 열쇠를 여세요. 배우기 쉽고 놓기 어렵습니다 — 끝없는 레벨에서 친구들과 경쟁하세요."),
        "vstep-practice": dict(tagline="실제 시험 형식 그대로 VSTEP 4개 영역 연습",
            desc="듣기, 읽기, 쓰기, 말하기 모의고사를 실제 VSTEP.3-5와 동일한 구성과 시간으로 응시할 수 있습니다. 이중 언어 스크립트와 스마트 복습 알림 제공. 무료, 오프라인 지원.",
            meta=["4개 영역 모두", "오프라인 지원"]),
    },
),
"zh": dict(
    page_title="TvTroid — 让学习变成游戏的应用",
    meta_desc="简洁精良的学习与娱乐移动应用。超过 217,000 人在使用我们的 TOEIC®、益智和国际象棋应用。",
    nav_apps="应用", nav_about="关于", nav_cta="获取应用",
    eyebrow_hero="由 TvTroid 打造",
    hero_l1="让学习", hero_l2="变成游戏的应用",
    hero_sub="超过 217,000 人使用我们的应用攻克 TOEIC®、用益智游戏锻炼大脑 — 免费下载，一试就爱上。",
    btn_explore="探索应用", btn_learn="了解更多",
    stat_installs="安装量", stat_rating="平均评分", stat_apps="已发布应用",
    eyebrow_apps="我们的应用", apps_h2="挑选你的下一个心头好",
    apps_sub="免费下载。简洁、快速，真正实用。",
    badge_popular="最受欢迎", badge_new="新品",
    installs_suffix="次安装",
    eyebrow_about="关于 TvTroid", about_h2="小团队。简单的应用。没有多余。",
    about_p="我们是一家独立工作室，专注于打造实用、不啰嗦的移动应用 — 从间隔重复学习工具到令人上瘾的益智游戏。每款应用都力求把一件事做好、加载迅速，并尊重你的时间。",
    f1_h="快速轻量", f1_p="没有臃肿与杂乱 — 只有你真正需要的功能。",
    f2_h="为目标而生", f2_p="每款应用都解决真实问题，并有学习科学作为支撑。",
    f3_h="尊重隐私", f3_p="我们始终将数据收集保持在最低限度并公开透明。",
    cta_h="准备好试试了吗？", cta_p="今天就下载任意一款 — 免费、快速，一键即得。",
    cta_btn="浏览全部应用",
    footer_tag="我们打造人们喜爱的应用",
    privacy="隐私政策", rights="TvTroid. 保留所有权利。",
    lang_label="语言",
    apps={
        "toeic-test": dict(tagline="用间隔重复攻克 TOEIC® 新题型",
            desc="超过 1,000 道真实 TOEIC® 题目，配合智能间隔重复引擎，帮你长久记住词汇和语法 — 而不只是撑到考试当天。"),
        "chess-ninja": dict(tagline="你能撑多久？",
            desc="吃掉敌方棋子夺取它们的能力，连续击杀叠加最高 ×8 连击奖励，在同一张棋盘上挺过无尽的进攻波次。免费游玩，无需账号。",
            meta=["6 种可用棋子", "免费游玩"]),
        "crack-the-code": dict(tagline="让你不断猜下去的无尽益智游戏",
            desc="找出每条谜题中隐藏的正确数字来解锁钥匙。易学难放下 — 在无尽关卡中与好友一较高下。"),
        "vstep-practice": dict(tagline="按真实考试形式练习 VSTEP 四项技能",
            desc="听力、阅读、写作、口语模拟测试完全对照真实 VSTEP.3-5 的结构和时间安排，配有双语文本和智能复习提醒。免费，支持离线使用。",
            meta=["覆盖四项技能", "支持离线"]),
    },
),
"th": dict(
    page_title="TvTroid — แอปที่ทำให้การเรียนรู้สนุกเหมือนเล่นเกม",
    meta_desc="แอปมือถือที่เรียบง่ายและประณีตเพื่อการเรียนรู้และความสนุก มีผู้ใช้กว่า 217,000 คนใช้แอป TOEIC® ปริศนา และหมากรุกของเรา",
    nav_apps="แอป", nav_about="เกี่ยวกับ", nav_cta="ดาวน์โหลดแอป",
    eyebrow_hero="สร้างโดย TvTroid",
    hero_l1="แอปที่ทำให้การเรียนรู้", hero_l2="สนุกเหมือนเล่นเกม",
    hero_sub="ผู้ใช้กว่า 217,000 คนใช้แอปของเราเพื่อพิชิต TOEIC® และฝึกสมองด้วยเกมปริศนา — ดาวน์โหลดฟรี ใช้แล้วติดใจ",
    btn_explore="สำรวจแอป", btn_learn="เรียนรู้เพิ่มเติม",
    stat_installs="ยอดติดตั้ง", stat_rating="คะแนนเฉลี่ย", stat_apps="แอปที่เปิดตัว",
    eyebrow_apps="แอปของเรา", apps_h2="เลือกแอปโปรดตัวต่อไปของคุณ",
    apps_sub="ดาวน์โหลดฟรี สร้างมาให้เรียบง่าย รวดเร็ว และมีประโยชน์จริง",
    badge_popular="ยอดนิยมที่สุด", badge_new="ใหม่",
    installs_suffix="การติดตั้ง",
    eyebrow_about="เกี่ยวกับ TvTroid", about_h2="ทีมเล็ก แอปเรียบง่าย ไม่มีอะไรเกินจำเป็น",
    about_p="เราเป็นสตูดิโออินดี้ที่มุ่งสร้างแอปมือถือที่มีประโยชน์และตรงไปตรงมา — ตั้งแต่เครื่องมือเรียนรู้แบบทบทวนเว้นช่วงไปจนถึงเกมปริศนาที่ชวนติดหนึบ ทุกแอปออกแบบมาให้ทำสิ่งเดียวได้ดี โหลดเร็ว และเคารพเวลาของคุณ",
    f1_h="เร็วและเบา", f1_p="ไม่อืด ไม่รก — มีแค่ฟีเจอร์ที่คุณต้องใช้จริง ๆ",
    f2_h="สร้างอย่างมีเป้าหมาย", f2_p="ทุกแอปแก้ปัญหาจริง โดยมีหลักวิทยาศาสตร์การเรียนรู้รองรับ",
    f3_h="เคารพความเป็นส่วนตัว", f3_p="เราเก็บข้อมูลให้น้อยที่สุดและโปร่งใสเสมอ",
    cta_h="พร้อมลองแล้วหรือยัง?", cta_p="ดาวน์โหลดแอปไหนก็ได้วันนี้ — ฟรี เร็ว และแตะเพียงครั้งเดียว",
    cta_btn="ดูแอปทั้งหมด",
    footer_tag="เราสร้างแอปที่ผู้คนรัก",
    privacy="นโยบายความเป็นส่วนตัว", rights="TvTroid. สงวนลิขสิทธิ์ทั้งหมด",
    lang_label="ภาษา",
    apps={
        "toeic-test": dict(tagline="พิชิต TOEIC® รูปแบบใหม่ด้วยการทบทวนเว้นช่วง",
            desc="ข้อสอบ TOEIC® จริงกว่า 1,000 ข้อ พร้อมระบบทบทวนเว้นช่วงอัจฉริยะที่ช่วยให้คุณจำคำศัพท์และไวยากรณ์ได้ยาว ๆ — ไม่ใช่แค่ถึงวันสอบ"),
        "chess-ninja": dict(tagline="คุณจะอยู่รอดได้นานแค่ไหน?",
            desc="จับหมากของศัตรูเพื่อขโมยพลัง ต่อคอมโบสังหารรับโบนัสสูงสุด ×8 และเอาตัวรอดจากคลื่นศัตรูไม่รู้จบบนกระดานเดียว เล่นฟรี ไม่ต้องสมัครบัญชี",
            meta=["หมาก 6 แบบ", "เล่นฟรี"]),
        "crack-the-code": dict(tagline="เกมปริศนาไม่รู้จบที่ท้าทายคุณตลอดเวลา",
            desc="ค้นหาตัวเลขที่ถูกต้องซึ่งซ่อนอยู่ในแต่ละปริศนาเพื่อปลดล็อกกุญแจ เรียนรู้ง่ายแต่วางไม่ลง — แข่งกับเพื่อนผ่านด่านไม่รู้จบ"),
        "vstep-practice": dict(tagline="ฝึกครบ 4 ทักษะ VSTEP ในรูปแบบข้อสอบจริง",
            desc="ข้อสอบจำลอง ฟัง อ่าน เขียน พูด ตรงตามโครงสร้างและเวลาของข้อสอบ VSTEP.3-5 จริง พร้อมบทถอดเสียงสองภาษาและระบบแจ้งเตือนทบทวนอัจฉริยะ ฟรี ใช้งานออฟไลน์ได้",
            meta=["ครบ 4 ทักษะ", "ใช้งานออฟไลน์ได้"]),
    },
),
"es": dict(
    page_title="TvTroid — Apps que hacen del aprendizaje un juego",
    meta_desc="Apps móviles sencillas y bien hechas para aprender y divertirse. Más de 217.000 personas usan nuestras apps de TOEIC®, puzzles y ajedrez.",
    nav_apps="Apps", nav_about="Acerca de", nav_cta="Descargar apps",
    eyebrow_hero="Creado por TvTroid",
    hero_l1="Apps que hacen del", hero_l2="aprendizaje un juego",
    hero_sub="Más de 217.000 personas usan nuestras apps para dominar el TOEIC® y ejercitar la mente con puzzles: gratis y fáciles de querer.",
    btn_explore="Explorar las apps", btn_learn="Saber más",
    stat_installs="Instalaciones", stat_rating="Valoración media", stat_apps="Apps publicadas",
    eyebrow_apps="Nuestras apps", apps_h2="Elige tu próxima app favorita",
    apps_sub="Descarga gratuita. Diseñadas para ser simples, rápidas y realmente útiles.",
    badge_popular="Más popular", badge_new="Nuevo",
    installs_suffix="instalaciones",
    eyebrow_about="Sobre TvTroid", about_h2="Equipo pequeño. Apps simples. Sin relleno.",
    about_p="Somos un estudio independiente centrado en crear apps móviles útiles y sin artificios: desde herramientas de aprendizaje con repetición espaciada hasta juegos de puzzle adictivos. Cada app está diseñada para hacer una cosa bien, cargar rápido y respetar tu tiempo.",
    f1_h="Rápidas y ligeras", f1_p="Sin excesos ni desorden: solo las funciones que realmente necesitas.",
    f2_h="Creadas con un propósito", f2_p="Cada app resuelve un problema real, respaldada por la ciencia del aprendizaje.",
    f3_h="Privacidad respetada", f3_p="Recopilamos los mínimos datos posibles, siempre de forma transparente.",
    cta_h="¿List@ para probarlas?", cta_p="Descarga hoy cualquiera de nuestras apps: gratis, rápido y a un solo toque.",
    cta_btn="Ver todas las apps",
    footer_tag="Creamos apps que la gente disfruta usar",
    privacy="Política de privacidad", rights="TvTroid. Todos los derechos reservados.",
    lang_label="Idioma",
    apps={
        "toeic-test": dict(tagline="Domina el nuevo formato TOEIC® con repetición espaciada",
            desc="Más de 1.000 preguntas reales del TOEIC® con un motor inteligente de repetición espaciada que te ayuda a retener vocabulario y gramática de verdad, no solo hasta el examen."),
        "chess-ninja": dict(tagline="¿Cuánto aguantarás?",
            desc="Captura piezas enemigas para robar sus poderes, encadena capturas para bonos de combo de hasta ×8 y sobrevive a oleadas infinitas en un solo tablero. Gratis, sin necesidad de cuenta.",
            meta=["6 piezas jugables", "Gratis"]),
        "crack-the-code": dict(tagline="Un puzzle infinito que te mantiene pensando",
            desc="Encuentra los números correctos ocultos en cada acertijo para desbloquear la llave. Fácil de aprender, difícil de soltar: compite con amigos en niveles infinitos."),
        "vstep-practice": dict(tagline="Practica las 4 destrezas del VSTEP en formato de examen real",
            desc="Exámenes simulados de Listening, Reading, Writing y Speaking con la estructura y el tiempo reales del VSTEP.3-5, con transcripciones bilingües y recordatorios de repaso inteligentes. Gratis y funciona sin conexión.",
            meta=["4 destrezas cubiertas", "Funciona sin conexión"]),
    },
),
"fr": dict(
    page_title="TvTroid — Des applis qui transforment l'apprentissage en jeu",
    meta_desc="Des applis mobiles simples et soignées pour apprendre et s'amuser. Plus de 217 000 personnes utilisent nos applis TOEIC®, puzzle et échecs.",
    nav_apps="Applis", nav_about="À propos", nav_cta="Télécharger",
    eyebrow_hero="Créé par TvTroid",
    hero_l1="Des applis qui transforment", hero_l2="l'apprentissage en jeu",
    hero_sub="Plus de 217 000 personnes utilisent nos applis pour réussir le TOEIC® et stimuler leur esprit avec des puzzles — gratuit et facile à adopter.",
    btn_explore="Découvrir les applis", btn_learn="En savoir plus",
    stat_installs="Installations", stat_rating="Note moyenne", stat_apps="Applis publiées",
    eyebrow_apps="Nos applis", apps_h2="Choisissez votre prochaine appli favorite",
    apps_sub="Téléchargement gratuit. Conçues pour être simples, rapides et vraiment utiles.",
    badge_popular="La plus populaire", badge_new="Nouveau",
    installs_suffix="installations",
    eyebrow_about="À propos de TvTroid", about_h2="Petite équipe. Applis simples. Sans superflu.",
    about_p="Nous sommes un studio indépendant qui conçoit des applis mobiles utiles et sans fioritures — des outils d'apprentissage à répétition espacée aux jeux de puzzle addictifs. Chaque appli est pensée pour faire une chose bien, se lancer vite et respecter votre temps.",
    f1_h="Rapides et légères", f1_p="Ni lourdeur ni encombrement — seulement les fonctions dont vous avez besoin.",
    f2_h="Conçues avec intention", f2_p="Chaque appli résout un vrai problème, appuyée sur la science de l'apprentissage.",
    f3_h="Vie privée respectée", f3_p="Nous collectons le minimum de données, en toute transparence. Toujours.",
    cta_h="Prêt à essayer ?", cta_p="Téléchargez l'une de nos applis aujourd'hui — gratuit, rapide, en un seul geste.",
    cta_btn="Voir toutes les applis",
    footer_tag="Nous créons des applis que les gens aiment utiliser",
    privacy="Politique de confidentialité", rights="TvTroid. Tous droits réservés.",
    lang_label="Langue",
    apps={
        "toeic-test": dict(tagline="Maîtrisez le nouveau format TOEIC® grâce à la répétition espacée",
            desc="Plus de 1 000 vraies questions du TOEIC® avec un moteur intelligent de répétition espacée qui vous aide à retenir durablement le vocabulaire et la grammaire — pas seulement jusqu'à l'examen."),
        "chess-ninja": dict(tagline="Combien de temps tiendrez-vous ?",
            desc="Capturez les pièces ennemies pour voler leurs pouvoirs, enchaînez les prises pour des bonus de combo jusqu'à ×8 et survivez à des vagues infinies sur un seul échiquier. Gratuit, sans compte.",
            meta=["6 pièces jouables", "Gratuit"]),
        "crack-the-code": dict(tagline="Un puzzle sans fin qui vous tient en haleine",
            desc="Trouvez les bons chiffres cachés dans chaque énigme pour déverrouiller la clé. Facile à apprendre, difficile à lâcher — affrontez vos amis sur des niveaux infinis."),
        "vstep-practice": dict(tagline="Entraînez les 4 compétences du VSTEP en conditions réelles",
            desc="Examens blancs de compréhension orale, compréhension écrite, expression écrite et expression orale au format et au minutage réels du VSTEP.3-5, avec transcriptions bilingues et rappels de révision intelligents. Gratuit, fonctionne hors ligne.",
            meta=["4 compétences couvertes", "Fonctionne hors ligne"]),
    },
),
"id": dict(
    page_title="TvTroid — Aplikasi yang membuat belajar terasa seperti bermain",
    meta_desc="Aplikasi seluler sederhana dan digarap rapi untuk belajar dan bersenang-senang. Lebih dari 217.000 orang memakai aplikasi TOEIC®, teka-teki, dan catur kami.",
    nav_apps="Aplikasi", nav_about="Tentang", nav_cta="Dapatkan aplikasi",
    eyebrow_hero="Dibuat oleh TvTroid",
    hero_l1="Aplikasi yang membuat", hero_l2="belajar terasa seperti bermain",
    hero_sub="Lebih dari 217.000 orang memakai aplikasi kami untuk menaklukkan TOEIC® dan mengasah otak dengan teka-teki — gratis diunduh, mudah disukai.",
    btn_explore="Jelajahi aplikasi", btn_learn="Pelajari lebih lanjut",
    stat_installs="Pemasangan", stat_rating="Rating rata-rata", stat_apps="Aplikasi dirilis",
    eyebrow_apps="Aplikasi kami", apps_h2="Pilih aplikasi favorit Anda berikutnya",
    apps_sub="Gratis diunduh. Dibuat agar sederhana, cepat, dan benar-benar berguna.",
    badge_popular="Paling populer", badge_new="Baru",
    installs_suffix="pemasangan",
    eyebrow_about="Tentang TvTroid", about_h2="Tim kecil. Aplikasi sederhana. Tanpa basa-basi.",
    about_p="Kami studio indie yang fokus membuat aplikasi seluler yang berguna dan tanpa basa-basi — dari alat belajar pengulangan berjarak hingga gim teka-teki yang bikin ketagihan. Setiap aplikasi dirancang untuk melakukan satu hal dengan baik, memuat cepat, dan menghargai waktu Anda.",
    f1_h="Cepat & ringan", f1_p="Tanpa beban berlebih, tanpa kekacauan — hanya fitur yang benar-benar Anda perlukan.",
    f2_h="Dibangun dengan tujuan", f2_p="Setiap aplikasi memecahkan masalah nyata, didukung ilmu pembelajaran.",
    f3_h="Privasi dihormati", f3_p="Kami menjaga pengumpulan data seminimal dan setransparan mungkin. Selalu.",
    cta_h="Siap mencoba?", cta_p="Unduh aplikasi mana pun hari ini — gratis, cepat, cukup satu ketukan.",
    cta_btn="Lihat semua aplikasi",
    footer_tag="Kami membuat aplikasi yang disukai orang",
    privacy="Kebijakan Privasi", rights="TvTroid. Semua hak dilindungi.",
    lang_label="Bahasa",
    apps={
        "toeic-test": dict(tagline="Kuasai TOEIC® Format Baru dengan pengulangan berjarak",
            desc="Lebih dari 1.000 soal TOEIC® asli dengan mesin pengulangan berjarak cerdas yang membantu Anda mengingat kosakata dan tata bahasa untuk selamanya — bukan hanya sampai hari ujian."),
        "chess-ninja": dict(tagline="Berapa lama Anda bisa bertahan?",
            desc="Tangkap bidak musuh untuk mencuri kekuatannya, rangkai tangkapan untuk bonus kombo hingga ×8, dan bertahanlah dari gelombang tanpa akhir di satu papan. Gratis dimainkan, tanpa perlu akun.",
            meta=["6 bidak dimainkan", "Gratis dimainkan"]),
        "crack-the-code": dict(tagline="Teka-teki tanpa akhir yang terus membuat Anda menebak",
            desc="Temukan angka yang benar tersembunyi di setiap teka-teki untuk membuka kunci. Mudah dipelajari, sulit dilepaskan — bersainglah dengan teman di level tanpa akhir."),
        "vstep-practice": dict(tagline="Latihan 4 keterampilan VSTEP dengan format ujian asli",
            desc="Tes simulasi Listening, Reading, Writing, dan Speaking sesuai struktur dan waktu ujian VSTEP.3-5 yang sebenarnya, dengan transkrip dwibahasa dan pengingat ulasan cerdas. Gratis, bisa dipakai offline.",
            meta=["4 keterampilan tercakup", "Bisa dipakai offline"]),
    },
),
"el": dict(
    page_title="TvTroid — Εφαρμογές που κάνουν τη μάθηση παιχνίδι",
    meta_desc="Απλές, καλοφτιαγμένες εφαρμογές για μάθηση και διασκέδαση. Πάνω από 217.000 άτομα χρησιμοποιούν τις εφαρμογές μας για TOEIC®, γρίφους και σκάκι.",
    nav_apps="Εφαρμογές", nav_about="Σχετικά", nav_cta="Αποκτήστε τις",
    eyebrow_hero="Από την TvTroid",
    hero_l1="Εφαρμογές που κάνουν", hero_l2="τη μάθηση παιχνίδι",
    hero_sub="Πάνω από 217.000 άτομα χρησιμοποιούν τις εφαρμογές μας για να κατακτήσουν το TOEIC® και να ακονίσουν το μυαλό τους με γρίφους — δωρεάν και εύκολα αγαπητές.",
    btn_explore="Εξερευνήστε τις εφαρμογές", btn_learn="Μάθετε περισσότερα",
    stat_installs="Εγκαταστάσεις", stat_rating="Μέση βαθμολογία", stat_apps="Εφαρμογές",
    eyebrow_apps="Οι εφαρμογές μας", apps_h2="Διαλέξτε την επόμενη αγαπημένη σας",
    apps_sub="Δωρεάν λήψη. Φτιαγμένες να είναι απλές, γρήγορες και πραγματικά χρήσιμες.",
    badge_popular="Πιο δημοφιλής", badge_new="Νέο",
    installs_suffix="εγκαταστάσεις",
    eyebrow_about="Σχετικά με την TvTroid", about_h2="Μικρή ομάδα. Απλές εφαρμογές. Χωρίς περιττά.",
    about_p="Είμαστε ένα ανεξάρτητο στούντιο που εστιάζει στη δημιουργία χρήσιμων, ουσιαστικών εφαρμογών — από εργαλεία μάθησης με διαστημική επανάληψη έως εθιστικά παιχνίδια γρίφων. Κάθε εφαρμογή σχεδιάζεται για να κάνει ένα πράγμα καλά, να φορτώνει γρήγορα και να σέβεται τον χρόνο σας.",
    f1_h="Γρήγορες & ελαφριές", f1_p="Χωρίς περιττά και ακαταστασία — μόνο όσα πραγματικά χρειάζεστε.",
    f2_h="Με σκοπό", f2_p="Κάθε εφαρμογή λύνει ένα πραγματικό πρόβλημα, με βάση την επιστήμη της μάθησης.",
    f3_h="Σεβασμός στα δεδομένα σας", f3_p="Συλλέγουμε ελάχιστα δεδομένα, πάντα με διαφάνεια.",
    cta_h="Έτοιμοι να δοκιμάσετε;", cta_p="Κατεβάστε όποια εφαρμογή θέλετε σήμερα — δωρεάν, γρήγορα, με ένα άγγιγμα.",
    cta_btn="Δείτε όλες τις εφαρμογές",
    footer_tag="Φτιάχνουμε εφαρμογές που ο κόσμος αγαπά",
    privacy="Πολιτική Απορρήτου", rights="TvTroid. Με επιφύλαξη παντός δικαιώματος.",
    lang_label="Γλώσσα",
    apps={
        "toeic-test": dict(tagline="Κατακτήστε το νέο TOEIC® με διαστημική επανάληψη",
            desc="Πάνω από 1.000 πραγματικές ερωτήσεις TOEIC® με έξυπνο σύστημα διαστημικής επανάληψης που σας βοηθά να συγκρατήσετε λεξιλόγιο και γραμματική μόνιμα — όχι μόνο μέχρι τις εξετάσεις."),
        "chess-ninja": dict(tagline="Πόσο θα αντέξετε;",
            desc="Αιχμαλωτίστε εχθρικά κομμάτια για να κλέψετε τις δυνάμεις τους, αλυσιδώστε συλλήψεις για μπόνους combo έως ×8 και επιβιώστε σε ατελείωτα κύματα σε μία σκακιέρα. Δωρεάν, χωρίς λογαριασμό.",
            meta=["6 κομμάτια", "Δωρεάν"]),
        "crack-the-code": dict(tagline="Ένας ατελείωτος γρίφος που σας κρατά σε εγρήγορση",
            desc="Βρείτε τους σωστούς αριθμούς που κρύβονται σε κάθε γρίφο για να ξεκλειδώσετε το κλειδί. Εύκολο να το μάθετε, δύσκολο να το αφήσετε — συναγωνιστείτε φίλους σε ατελείωτα επίπεδα."),
        "vstep-practice": dict(tagline="Εξασκηθείτε και στις 4 δεξιότητες του VSTEP σε πραγματική μορφή εξέτασης",
            desc="Δοκιμαστικές εξετάσεις Listening, Reading, Writing και Speaking με τη δομή και τον χρόνο της πραγματικής εξέτασης VSTEP.3-5, με δίγλωσσες απομαγνητοφωνήσεις και έξυπνες υπενθυμίσεις επανάληψης. Δωρεάν, λειτουργεί χωρίς σύνδεση.",
            meta=["Καλύπτει 4 δεξιότητες", "Λειτουργεί χωρίς σύνδεση"]),
    },
),
}
