name: Daily

on:
  schedule:
    - cron:  "0 1 * * *"

jobs:
  run:
    name: Create new questions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run script
        run: |
          ./questions.sh
      
    name: Deploy to gist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy 2
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: 9edd387ef4cf66734c0cf2d1ac2a798f
          file_path: ./dist/2.txt
      - name: Deploy 3
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: 55633d095690bad521488b264ebfc0be
          file_path: ./dist/3.txt
      - name: Deploy 4
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: de9a8ca788162b6413293bb3b9ca7dd2
          file_path: ./dist/4.txt
      - name: Deploy 5
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: fa853a8fadbd008cb701e445bd0bc979
          file_path: ./dist/5.txt
