name: Daily

on:
  workflow_dispatch:
  schedule:
    - cron:  "0 1 * * *"

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate 2
        id: generate_2
        working-directory: ./.github/workflows
        run: |
          question2=$(./new2.sh)
          echo ::set-output name=question2::$(echo ${question2})
      - name: Write to 2
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ./dist/2.txt
          contents: |
            ${{ steps.generate_2.outputs.question2 }}
          write-mode: overwrite
      - name: Deploy 2
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: 9edd387ef4cf66734c0cf2d1ac2a798f
          file_path: ./dist/2.txt

      - name: Generate 3
        id: generate_3
        working-directory: ./.github/workflows
        run: |
          question3=$(./new3.sh)
          echo ::set-output name=question3::$(echo ${question3})
      - name: Write to 3
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ./dist/3.txt
          contents: |
            ${{ steps.generate_3.outputs.question3 }}
          write-mode: overwrite
      - name: Deploy 3
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: 55633d095690bad521488b264ebfc0be
          file_path: ./dist/3.txt
      
      - name: Generate 4
        id: generate_4
        working-directory: ./.github/workflows
        run: |
          question4=$(./new4.sh)
          echo ::set-output name=question4::$(echo ${question4})
      - name: Write to 4
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ./dist/4.txt
          contents: |
            ${{ steps.generate_4.outputs.question4 }}
          write-mode: overwrite
      - name: Deploy 4
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: de9a8ca788162b6413293bb3b9ca7dd2
          file_path: ./dist/4.txt
          
      - name: Generate 5
        id: generate_5
        working-directory: ./.github/workflows
        run: |
          question5=$(./new5.sh)
          echo ::set-output name=question5::$(echo ${question5})
      - name: Write to 5
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ./dist/5.txt
          contents: |
            ${{ steps.generate_5.outputs.question5 }}
          write-mode: overwrite
      - name: Deploy 5
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: fa853a8fadbd008cb701e445bd0bc979
          file_path: ./dist/5.txt
