name: Daily

on:
  schedule:
    - cron:  "* * * */12 *"

jobs:
  assign:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: 3a49c2f1692cb5e3a4af6f8fd4bbfa10
          file_path: ./dist/test.txt
